# Generated by Django 3.1.6 on 2021-02-17 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('height', models.CharField(max_length=255, verbose_name='Рост')),
                ('size', models.CharField(max_length=255, verbose_name='Размер_одежды')),
                ('sizeshoe', models.CharField(max_length=255, verbose_name='Размер_обуви')),
                ('place', models.CharField(max_length=255, verbose_name='Адрес_локации')),
                ('date', models.CharField(max_length=255, verbose_name='Дата_время')),
                ('time', models.CharField(max_length=255, verbose_name='Время_занятости')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Требования')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ставка')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
