# Generated by Django 3.1.6 on 2021-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210219_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='category',
            field=models.CharField(default=0, max_length=255, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='casting',
            name='fee',
            field=models.CharField(default=0, max_length=255, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='casting',
            name='hour',
            field=models.CharField(default=0, max_length=255, verbose_name='Время_занятости'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='date',
            field=models.CharField(default=0, max_length=255, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='description',
            field=models.TextField(blank=True, default=0, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='height',
            field=models.CharField(default=0, max_length=255, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='place',
            field=models.CharField(default=0, max_length=255, verbose_name='Адрес_локации'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='size',
            field=models.CharField(default=0, max_length=255, verbose_name='Размер_одежды'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='sizeshoe',
            field=models.CharField(default=0, max_length=255, verbose_name='Размер_обуви'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='time',
            field=models.CharField(default=0, max_length=255, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Наименование'),
        ),
    ]
