# Generated by Django 3.1.6 on 2021-02-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_pass_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
