# Generated by Django 3.1.6 on 2021-03-04 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired', models.BooleanField(default=False)),
                ('checked_out', models.BooleanField(default=False)),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.casting', verbose_name='Кастинг')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Актер')),
            ],
        ),
    ]
